package com.felicekarl.foragingtech.listeners;

public interface UpdateControllerNavigatingFragmentButtonListener {
	public void updateControllerNavigatingFragmentButtonListener(
			ControllerNavigatingFragmentButtonListener mControllerNavigatingFragmentButtonListener);
}
