package com.felicekarl.foragingtech.listeners;

public interface UpdateContentActionBarFragmentButtonListener {
	public void updateContentActionBarFragmentButtonListener(ContentActionBarFragmentButtonListener mContentActionBarFragmentButtonListener);
}
